options(digits=8)
a <- read.csv('~/lstange/mcgs/es_omp_avx2.csv')
m <- read.csv('~/lstange/mcgs/es_omp_avx2_mcg.csv')
png(filename='~/lstange/mcgs/es.png', width=920, height=640, pointsize=24)
plot.ecdf(a$avg, main='Extreme Spread of 5-shot Group')
plot.ecdf(m$avg, add=T)
dev.off()
ks.test(a$avg, m$avg)
x <- rbind(a, m)
mean(x$avg)
mean(x$avg)-2*sd(a$avg)/sqrt(nrow(x))
mean(x$avg)+2*sd(a$avg)/sqrt(nrow(x))
