options(digits=8)
a <- read.csv('~/lstange/mcgs/es_omp_avx2.csv')
m <- read.csv('~/lstange/mcgs/es_omp_avx2_mcg.csv')
c <- read.csv('~/lstange/mcgs/es_cuda.csv')
png(filename='~/lstange/mcgs/es.png', width=920, height=640, pointsize=24)
plot.ecdf(a$avg, main='Extreme Spread of 5-shot Group',col='red',xlim=c(3.06585,3.0659))
plot.ecdf(m$avg, add=T, col='green')
plot.ecdf(c$avg, add=T, col='blue')
legend('bottomright', legend=c('AVX2','CPU','CUDA'),
       col=c('red','green','blue'),lty=c(1,1,1),pch==c(16,16,16))
dev.off()
ks.test(a$avg, m$avg)
ks.test(a$avg, c$avg)
x <- rbind(a, m)
x <- rbind(x, c)
mean(x$avg)
mean(x$avg)-2*sd(a$avg)/sqrt(nrow(x))
mean(x$avg)+2*sd(a$avg)/sqrt(nrow(x))
